spring.application.name=hostelhub

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:hostelhub}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:system}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8082}

jwt.secret=${JWT_SECRET:hostelhub-super-secret-key-for-jwt-authentication-must-be-256-bits}
jwt.expiration=86400000

spring.jpa.open-in-view=true
spring.jackson.serialization.write-dates-as-timestamps=false